//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::PaymentStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "payment")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub amount: i64,
    pub currency: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", unique)]
    pub razorpay_payment_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub razorpay_order_id: Option<String>,
    pub payment_status: PaymentStatus,
    pub subscription_id: Option<Uuid>,
    pub user_id: Uuid,
    #[sea_orm(
        belongs_to,
        from = "subscription_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub subscription: HasOne<super::subscription::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
