//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "link_type")]
pub enum LinkType {
    #[sea_orm(string_value = "torrent")]
    Torrent,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "payment_status")]
pub enum PaymentStatus {
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "authorized")]
    Authorized,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
    #[sea_orm(string_value = "captured")]
    Captured,
    #[sea_orm(string_value = "refunded")]
    Refunded,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "provider")]
pub enum Provider {
    #[sea_orm(string_value = "Google")]
    Google,
    #[sea_orm(string_value = "Mega")]
    Mega,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "quota_type")]
pub enum QuotaType {
    #[sea_orm(string_value = "Free")]
    Free,
    #[sea_orm(string_value = "Bronze")]
    Bronze,
    #[sea_orm(string_value = "Silver")]
    Silver,
    #[sea_orm(string_value = "Gold")]
    Gold,
    #[sea_orm(string_value = "Platinum")]
    Platinum,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "status")]
pub enum Status {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "completed")]
    Completed,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "sub_status")]
pub enum SubStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
    #[sea_orm(string_value = "expired")]
    Expired,
    #[sea_orm(string_value = "pending")]
    Pending,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "transfer_type")]
pub enum TransferType {
    #[sea_orm(string_value = "google_to_google")]
    GoogleToGoogle,
    #[sea_orm(string_value = "mega_to_google")]
    MegaToGoogle,
}
