name: Build ARM64 Static Binaries

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: messense/rust-musl-cross:aarch64-musl

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          cargo build \
            --release \
            --target aarch64-unknown-linux-musl4
      - name: Verify
        run: file target/aarch64-unknown-linux-musl/release/api

      - name: Collect binaries
        run: |
          mkdir -p artifacts

          cp target/aarch64-unknown-linux-musl/release/api artifacts/
          cp target/aarch64-unknown-linux-musl/release/ws artifacts/
          cp target/aarch64-unknown-linux-musl/release/refresh-service artifacts/
          cp target/aarch64-unknown-linux-musl/release/transfer-service artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: unicloud-aarch64-binaries
          path: backend/artifacts/*
